/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogisticaRouteImport } from './routes/logistica'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as CampoRouteImport } from './routes/campo'
import { Route as IndexRouteImport } from './routes/index'

const LogisticaRoute = LogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoRoute = CampoRouteImport.update({
  id: '/campo',
  path: '/campo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campo': typeof CampoRoute
  '/financeiro': typeof FinanceiroRoute
  '/logistica': typeof LogisticaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campo': typeof CampoRoute
  '/financeiro': typeof FinanceiroRoute
  '/logistica': typeof LogisticaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campo': typeof CampoRoute
  '/financeiro': typeof FinanceiroRoute
  '/logistica': typeof LogisticaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/campo' | '/financeiro' | '/logistica'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/campo' | '/financeiro' | '/logistica'
  id: '__root__' | '/' | '/campo' | '/financeiro' | '/logistica'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampoRoute: typeof CampoRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LogisticaRoute: typeof LogisticaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logistica': {
      id: '/logistica'
      path: '/logistica'
      fullPath: '/logistica'
      preLoaderRoute: typeof LogisticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo': {
      id: '/campo'
      path: '/campo'
      fullPath: '/campo'
      preLoaderRoute: typeof CampoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampoRoute: CampoRoute,
  FinanceiroRoute: FinanceiroRoute,
  LogisticaRoute: LogisticaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
